// crates/thunder-node/src/config.rs
//
// Thunder Node — Configuration and Persistent State
// ═══════════════════════════════════════════════════
//
// Config file location (platform-appropriate):
//   Linux:   ~/.config/thunder-node/config.toml
//   macOS:   ~/Library/Application Support/thunder-node/config.toml
//   Windows: %APPDATA%\thunder-node\config.toml
//
// The config file is created by `thunder setup` with safe defaults.
// Operators edit it to configure relay nodes, fees, and key rotation schedule.

use std::path::{Path, PathBuf};
use std::fs;
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("Config file not found at {0}. Run `thunder setup` to generate it.")]
    NotFound(PathBuf),
    #[error("Config parse error: {0}")]
    Parse(String),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

/// Top-level Thunder Node configuration file (config.toml).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThunderConfig {
    /// Node identity (display name only — not used for routing)
    #[serde(default = "default_node_name")]
    pub node_name: String,

    /// Fee settings
    #[serde(default)]
    pub fees: FeeConfig,

    /// LND connection
    #[serde(default)]
    pub lnd: LndConnectionConfig,

    /// Tor settings
    #[serde(default)]
    pub tor: TorConnectionConfig,

    /// Relay peers (other Thunder/relay nodes)
    #[serde(default)]
    pub relays: Vec<RelayPeerConfig>,

    /// Key rotation
    #[serde(default)]
    pub rotation: RotationConfig,

    /// Logging
    #[serde(default)]
    pub logging: LogConfig,
}

fn default_node_name() -> String { "Thunder Node".to_string() }

impl Default for ThunderConfig {
    fn default() -> Self {
        ThunderConfig {
            node_name: default_node_name(),
            fees:      FeeConfig::default(),
            lnd:       LndConnectionConfig::default(),
            tor:       TorConnectionConfig::default(),
            relays:    vec![],
            rotation:  RotationConfig::default(),
            logging:   LogConfig::default(),
        }
    }
}

/// Fee configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeeConfig {
    /// Operator cut in basis points (100 = 1%). Range: [1, 500].
    pub operator_fee_bps: u32,

    /// LN fee multiplier (2 = 2× standard LN fee). Range: [1, 5].
    pub fee_multiplier: u32,

    /// Operator stealth wallet spend public key (hex, 32 bytes).
    /// Generated by `thunder setup --generate-wallet`.
    /// The relay process only ever uses the view pubkey; the spend privkey
    /// lives on your air-gapped device.
    pub operator_spend_pubkey_hex: String,

    /// Operator stealth wallet view public key (hex, 32 bytes).
    pub operator_view_pubkey_hex: String,
}

impl Default for FeeConfig {
    fn default() -> Self {
        FeeConfig {
            operator_fee_bps:          100,   // 1%
            fee_multiplier:            2,     // 2× LN
            operator_spend_pubkey_hex: String::new(),
            operator_view_pubkey_hex:  String::new(),
        }
    }
}

/// LND gRPC connection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LndConnectionConfig {
    /// LND gRPC endpoint. Default: localhost for Tor-only mode.
    pub endpoint: String,
    /// Path to LND TLS certificate.
    pub tls_cert_path: String,
    /// LND admin macaroon as a hex string (not a file path).
    /// Generate with: xxd -p ~/.lnd/data/chain/bitcoin/signet/admin.macaroon | tr -d '\n'
    pub macaroon_hex: String,
    /// Payment timeout in seconds.
    pub timeout_secs: u64,
}

impl Default for LndConnectionConfig {
    fn default() -> Self {
        let lnd_dir = default_lnd_dir();
        LndConnectionConfig {
            endpoint:       "https://localhost:10009".to_string(),
            tls_cert_path:  lnd_dir.join("tls.cert").display().to_string(),
            macaroon_hex:   String::new(), // set via: xxd -p ~/.lnd/.../admin.macaroon | tr -d '\n'
            timeout_secs:   30,
        }
    }
}

/// Tor configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TorConnectionConfig {
    /// SOCKS5 proxy address.
    pub socks5_proxy: String,
    /// Tor control port.
    pub control_port: u16,
    /// Reject any clearnet (non-Tor) connections.
    pub clearnet_reject: bool,
    /// Your node's .onion address (set after running `thunder setup`).
    pub onion_address: String,
}

impl Default for TorConnectionConfig {
    fn default() -> Self {
        TorConnectionConfig {
            socks5_proxy:    "127.0.0.1:9050".to_string(),
            control_port:    9051,
            clearnet_reject: true,
            onion_address:   String::new(),
        }
    }
}

/// A relay peer node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayPeerConfig {
    /// Relay node's LND pubkey (hex, 33 bytes compressed secp256k1).
    pub pubkey_hex: String,
    /// Relay node's .onion address (v3).
    pub onion_address: String,
    /// Private channel ID to this relay (set after opening the channel).
    pub channel_id: u64,
    /// Max amount this relay will forward (millisatoshis).
    pub max_forward_msat: u64,
}

/// Key rotation configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RotationConfig {
    /// Enable automatic key rotation.
    pub enabled: bool,
    /// Rotation interval in days.
    pub interval_days: u32,
}

impl Default for RotationConfig {
    fn default() -> Self {
        RotationConfig { enabled: true, interval_days: 30 }
    }
}

/// Logging configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogConfig {
    /// Log level: error, warn, info, debug, trace
    pub level: String,
    /// Log to file (in addition to stdout)
    pub file: Option<String>,
}

impl Default for LogConfig {
    fn default() -> Self {
        LogConfig { level: "info".to_string(), file: None }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// PATHS
// ─────────────────────────────────────────────────────────────────────────────

/// Returns the platform-appropriate config directory.
///
/// - Linux/macOS: ~/.config/thunder-node/
/// - Windows:     %APPDATA%\thunder-node\
pub fn config_dir() -> PathBuf {
    let base = if cfg!(target_os = "windows") {
        std::env::var("APPDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|_| dirs_home().join("AppData/Roaming"))
    } else if cfg!(target_os = "macos") {
        dirs_home().join("Library/Application Support")
    } else {
        std::env::var("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|_| dirs_home().join(".config"))
    };
    base.join("thunder-node")
}

pub fn config_file() -> PathBuf {
    config_dir().join("config.toml")
}

pub fn data_dir() -> PathBuf {
    if cfg!(target_os = "windows") {
        std::env::var("APPDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|_| dirs_home().join("AppData/Roaming"))
            .join("thunder-node/data")
    } else if cfg!(target_os = "macos") {
        dirs_home().join("Library/Application Support/thunder-node/data")
    } else {
        std::env::var("XDG_DATA_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|_| dirs_home().join(".local/share"))
            .join("thunder-node")
    }
}

fn dirs_home() -> PathBuf {
    std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/tmp"))
}

fn default_lnd_dir() -> PathBuf {
    if cfg!(target_os = "windows") {
        dirs_home().join("AppData/Local/Lnd")
    } else {
        dirs_home().join(".lnd")
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// LOAD / SAVE
// ─────────────────────────────────────────────────────────────────────────────

impl ThunderConfig {
    /// Load config from the default platform path.
    pub fn load() -> Result<Self, ConfigError> {
        Self::load_from(&config_file())
    }

    /// Load config from a specific path.
    pub fn load_from(path: &Path) -> Result<Self, ConfigError> {
        if !path.exists() {
            return Err(ConfigError::NotFound(path.to_path_buf()));
        }
        let content = fs::read_to_string(path)?;
        toml::from_str(&content)
            .map_err(|e| ConfigError::Parse(e.to_string()))
    }

    /// Save config to the default platform path, creating the directory if needed.
    pub fn save(&self) -> Result<(), ConfigError> {
        let path = config_file();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let content = toml::to_string_pretty(self)
            .map_err(|e| ConfigError::Parse(e.to_string()))?;
        fs::write(&path, content)?;
        Ok(())
    }

    /// Generate the default config file with all values commented and documented.
    /// This is what `thunder setup` writes to disk.
    pub fn generate_default_toml(onion_address: &str) -> String {
        format!(
            r#"# ⚡ Thunder Node — Configuration
# ════════════════════════════════════════════════════
# Generated by `thunder setup`. Edit as needed.
# Full documentation: https://github.com/S6dative/vusd-protocol

# Display name for this node (not used for routing — purely informational)
node_name = "Thunder Node"

[fees]
# Operator fee in basis points (100 = 1%, range 1–500)
# This is your cut of every transfer relayed through this node.
# Routes to your VUSD stealth wallet — not a Lightning address.
operator_fee_bps = 100

# Fee multiplier on standard Lightning base fee (1 = 1×, 2 = 2×)
# 2× signals to users that their transfer is wrapped in privacy infrastructure.
fee_multiplier = 2

# Your operator stealth wallet public keys (hex, 32 bytes each)
# Generate with: thunder setup --generate-wallet
# NEVER put your spend PRIVATE key here.
operator_spend_pubkey_hex = ""
operator_view_pubkey_hex  = ""

[lnd]
# LND gRPC endpoint (localhost because Tor handles the network)
endpoint       = "https://localhost:10009"
tls_cert_path  = "{lnd_dir}/tls.cert"
macaroon_hex   = ""  # xxd -p ~/.lnd/data/chain/bitcoin/signet/admin.macaroon | tr -d '\n'
timeout_secs   = 30

[tor]
# SOCKS5 proxy where Tor is listening
socks5_proxy    = "127.0.0.1:9050"
control_port    = 9051
# Refuse ALL non-Tor connections — set false only for local testing
clearnet_reject = true
# Your node's .onion address (run `cat /var/lib/tor/vultd-lnd/hostname`)
onion_address   = "{onion}"

# Relay peers — other Thunder Nodes you have private channels with
# Add one [[relays]] section per peer.
# [[relays]]
# pubkey_hex      = "aabbcc..."    # LND node pubkey (hex, 33 bytes)
# onion_address   = "abc123.onion" # relay's .onion address
# channel_id      = 123456789      # private channel ID (from `lncli listchannels`)
# max_forward_msat = 10000000      # max 10,000 sat per forward

[rotation]
# Rotate node identity keypair every N days
# Closes old channels and opens new ones under a new pubkey
enabled       = true
interval_days = 30

[logging]
# Log level: error | warn | info | debug | trace
level = "info"
# Uncomment to log to file:
# file = "/var/log/thunder-node.log"
"#,
            lnd_dir = if cfg!(windows) { "%APPDATA%\\Lnd" } else { "~/.lnd" },
            onion   = onion_address,
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// TESTS
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config_serializes() {
        let cfg     = ThunderConfig::default();
        let toml    = toml::to_string_pretty(&cfg).unwrap();
        let parsed: ThunderConfig = toml::from_str(&toml).unwrap();
        assert_eq!(parsed.fees.operator_fee_bps, 100);
        assert_eq!(parsed.fees.fee_multiplier,   2);
        assert!(parsed.rotation.enabled);
    }

    #[test]
    fn test_generate_default_toml_contains_key_fields() {
        let toml = ThunderConfig::generate_default_toml("abc123.onion");
        assert!(toml.contains("operator_fee_bps = 100"));
        assert!(toml.contains("fee_multiplier = 2"));
        assert!(toml.contains("clearnet_reject = true"));
        assert!(toml.contains("abc123.onion"));
        assert!(toml.contains("interval_days = 30"));
    }

    #[test]
    fn test_config_roundtrip_with_relay() {
        let mut cfg = ThunderConfig::default();
        cfg.relays.push(RelayPeerConfig {
            pubkey_hex:       "aa".repeat(33),
            onion_address:    "test123.onion".to_string(),
            channel_id:       999_888_777,
            max_forward_msat: 5_000_000,
        });
        let toml: String = toml::to_string_pretty(&cfg).unwrap();
        let parsed: ThunderConfig = toml::from_str(&toml).unwrap();
        assert_eq!(parsed.relays.len(), 1);
        assert_eq!(parsed.relays[0].channel_id, 999_888_777);
        assert_eq!(parsed.relays[0].onion_address, "test123.onion");
    }

    #[test]
    fn test_config_dir_is_not_empty() {
        let dir = config_dir();
        assert!(dir.to_string_lossy().contains("thunder-node"));
    }

    #[test]
    fn test_data_dir_separate_from_config_dir() {
        let cfg  = config_dir();
        let data = data_dir();
        assert_ne!(cfg, data);
    }
}
